version: "3"

networks:
  default:
    external:
      name: bodego-dev-network

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=bodegodb
    volumes:
      - ../app/db/sql/init/:/docker-entrypoint-initdb.d/
  bodegoserver:
    container_name: bodegoserver
    build:
      context: ..
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    volumes:
      - ../:/usr/src/app
