version: "3"

networks:
  default:
    external:
      name: cartly-dev-network

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=cartlydb
    volumes:
      - ../app/db/sql/:/docker-entrypoint-initdb.d/
  cartlyserver:
    container_name: cartlyserver
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../:/usr/src/app
