-- -- Insert rows into table 'Products'
-- INSERT INTO Products
-- ( -- columns to insert data into
--  [Column1], [Column2], [Column3]
-- )
-- VALUES
-- (
--  Column1_Value, Column2_Value, Column3_Value
-- ),
-- (
--  Column1_Value, Column2_Value, Column3_Value
-- )
-- -- add more rows here
-- GO